"""Canonical platform catalogue and runtime provider bridge.

Keep platform-facing metadata here rather than scattering slightly different
choice lists throughout models, forms, and services. The registry is an
ordered tuple so generated choices remain stable across migrations.

Runtime provider implementations live in ``provider_registry``. ``get_provider``
bridges canonical platform keys to their concrete output-service adapters.
"""

from dataclasses import replace
from .publishing_defaults import builtin_modes
from .manifest import CAPABILITIES, PlatformManifest


CATEGORY_REGISTRY = {
    'messaging': {'order': 10, 'title_fa': 'پیام‌رسان‌ها', 'title_en': 'Messaging'},
    'video': {'order': 20, 'title_fa': 'ویدئومحور', 'title_en': 'Video'},
    'social_content': {
        'order': 30,
        'title_fa': 'شبکه‌های اجتماعی محتوایی',
        'title_en': 'Content social networks',
    },
    'location': {'order': 40, 'title_fa': 'مکان‌محور', 'title_en': 'Location based'},
    'general_social': {
        'order': 50,
        'title_fa': 'شبکه‌های اجتماعی عمومی',
        'title_en': 'General social networks',
    },
    'professional': {
        'order': 60,
        'title_fa': 'شبکه‌های حرفه‌ای',
        'title_en': 'Professional networks',
    },
}


# Compatibility name for historical catalogue imports.
PlatformDefinition = PlatformManifest


def _caps(**overrides):
    values = dict.fromkeys(CAPABILITIES, 'not_available')
    values.update(overrides)
    return values


def _capabilities(*values):
    return frozenset(values)


PLATFORM_REGISTRY = (
    PlatformDefinition(
        'facebook',
        'فیس‌بوک',
        'Facebook',
        'general_social',
        'شبکه‌های اجتماعی عمومی',
        'oauth2',
        _capabilities(
            'publish_text',
            'publish_image',
            'publish_video',
            'analytics',
            'inbox',
            'comments',
            'oauth',
        ),
        'facebook',
        'active',
        support=_caps(
            connection='supported',
            disconnect='supported',
            publish_text='supported',
            publish_image='supported',
            publish_video='supported',
            scheduling='supported',
            analytics='supported',
            inbox='supported',
            comments='supported',
            reviews='not_available',
            webhooks='supported',
        ),
        publisher='social_stats.publishers.facebook.FacebookPublisher',
        egress_service='meta',
        connection_handler='social_stats.views.oauth.oauth_disconnect',
        icon='facebook',
        brand_color='#1877F2',
        oauth_start='/api/oauth/facebook/start/{workspace_id}/',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'instagram',
        'اینستاگرام',
        'Instagram',
        'social_content',
        'شبکه‌های اجتماعی محتوایی',
        'oauth2',
        _capabilities(
            'publish_image', 'publish_video', 'analytics', 'inbox', 'comments', 'oauth'
        ),
        'instagram',
        'active',
        support=_caps(
            connection='supported',
            disconnect='supported',
            publish_text='not_available',
            publish_image='supported',
            publish_video='supported',
            scheduling='supported',
            analytics='supported',
            inbox='supported',
            comments='supported',
            reviews='not_available',
            webhooks='supported',
        ),
        publisher='social_stats.publishers.instagram.InstagramPublisher',
        egress_service='meta',
        connection_handler='social_stats.views.oauth.oauth_disconnect',
        icon='instagram',
        brand_color='#E1306C',
        oauth_start='/api/oauth/facebook/start/{workspace_id}/?platform=instagram',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'linkedin',
        'لینکدین',
        'LinkedIn',
        'professional',
        'شبکه‌های حرفه‌ای',
        'oauth2',
        _capabilities(
            'publish_text',
            'publish_image',
            'publish_video',
            'analytics',
            'comments',
            'oauth',
        ),
        'linkedin',
        'active',
        support=_caps(
            connection='supported',
            disconnect='supported',
            publish_text='supported',
            publish_image='supported',
            publish_video='supported',
            scheduling='supported',
            analytics='beta',
            comments='beta',
        ),
        publisher='social_stats.publishers.linkedin.LinkedInPublisher',
        egress_service='linkedin',
        connection_handler='social_stats.views.oauth.oauth_disconnect',
        icon='linkedin',
        brand_color='#0A66C2',
        oauth_start='/api/oauth/linkedin/start/{workspace_id}/',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'tiktok',
        'تیک‌تاک',
        'TikTok',
        'social_content',
        'شبکه‌های اجتماعی محتوایی',
        'oauth2',
        _capabilities('publish_video', 'analytics', 'comments', 'oauth'),
        'tiktok',
        'experimental',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'telegram',
        'تلگرام',
        'Telegram',
        'messaging',
        'پیام‌رسان‌ها',
        'bot_token',
        _capabilities('publish_text', 'publish_image', 'publish_video', 'comments'),
        'telegram',
        'active',
        support=_caps(
            connection='supported',
            disconnect='supported',
            publish_text='supported',
            publish_image='supported',
            publish_video='supported',
            scheduling='supported',
            analytics='not_available',
            inbox='supported',
            comments='not_available',
            reviews='not_available',
            webhooks='supported',
        ),
        publisher='social_stats.publishers.telegram.TelegramPublisher',
        egress_service='telegram',
        connection_handler='social_stats.views.bot_channel.bot_channel_connection',
        ui_extensions=('telegram_settings', 'telegram_composer'),
        icon='telegram',
        brand_color='#229ED9',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'bale',
        'بله',
        'Bale',
        'messaging',
        'پیام‌رسان‌ها',
        'bot_token',
        _capabilities('publish_text', 'publish_image', 'publish_video'),
        'bale',
        'active',
        support=_caps(
            connection='supported',
            disconnect='supported',
            publish_text='supported',
            publish_image='supported',
            publish_video='supported',
            scheduling='supported',
            analytics='not_available',
            inbox='planned',
            comments='not_available',
            reviews='not_available',
            webhooks='planned',
        ),
        publisher='social_stats.publishers.bale.BalePublisher',
        egress_service='bale',
        connection_handler='social_stats.views.bot_channel.bot_channel_connection',
        icon='bale',
        brand_color='#00A884',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'eitaa',
        'ایتا',
        'Eitaa',
        'messaging',
        'پیام‌رسان‌ها',
        'bot_token',
        _capabilities('publish_text', 'publish_image', 'publish_video'),
        'eitaa',
        'experimental',
        support=_caps(
            connection='planned',
            disconnect='planned',
            publish_text='planned',
            publish_image='planned',
            publish_video='planned',
            scheduling='planned',
            analytics='not_available',
            inbox='planned',
            comments='not_available',
            reviews='not_available',
            webhooks='planned',
        ),
        icon='eitaa',
        brand_color='#F58220',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'youtube',
        'یوتیوب',
        'YouTube',
        'video',
        'ویدئومحور',
        'oauth2',
        _capabilities('publish_video', 'analytics', 'comments', 'oauth'),
        'youtube',
        'active',
        support=_caps(
            connection='supported',
            disconnect='supported',
            publish_video='supported',
            scheduling='supported',
            analytics='supported',
            comments='supported',
            webhooks='beta',
        ),
        publisher='social_stats.publishers.youtube.YouTubePublisher',
        egress_service='google',
        connection_handler='social_stats.views.oauth.oauth_disconnect',
        icon='youtube',
        brand_color='#FF0000',
        oauth_start='/api/oauth/google/start/{workspace_id}/?platform=youtube',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'aparat',
        'آپارات',
        'Aparat',
        'video',
        'ویدئومحور',
        'api_key',
        _capabilities('publish_video', 'analytics', 'comments'),
        'aparat',
        'experimental',
        support=_caps(
            connection='planned',
            disconnect='planned',
            publish_video='planned',
            scheduling='planned',
            analytics='planned',
            comments='planned',
            webhooks='planned',
        ),
        icon='aparat',
        brand_color='#ED145B',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'google_my_business',
        'کسب‌وکار گوگل',
        'Google Business Profile',
        'location',
        'مکان‌محور',
        'oauth2',
        _capabilities('publish_text', 'publish_image', 'analytics', 'reviews', 'oauth'),
        'gmb',
        'active',
        support=_caps(
            connection='supported',
            disconnect='supported',
            publish_text='supported',
            publish_image='supported',
            scheduling='supported',
            analytics='supported',
            reviews='supported',
        ),
        publisher='social_stats.publishers.gmb.GMBPublisher',
        egress_service='google',
        connection_handler='social_stats.views.oauth.oauth_disconnect',
        icon='google_my_business',
        brand_color='#34A853',
        oauth_start='/api/oauth/google/start/{workspace_id}/?platform=google_my_business',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
    PlatformDefinition(
        'neshan',
        'نشان',
        'Neshan',
        'location',
        'مکان‌محور',
        'api_key',
        _capabilities('analytics', 'reviews'),
        'neshan',
        'experimental',
        legacy_adapter=True,
        destination_types=(
            'channel',
            'group',
            'profile',
            'business',
            'location',
            'topic',
        ),
    ),
)


# Enrich builtin compatibility contracts without a feature-level provider switch.
PLATFORM_REGISTRY = tuple(replace(item, publishing_modes=builtin_modes(item)) for item in PLATFORM_REGISTRY)
