# Generated by Django 5.2.17 on 2026-09-30 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0064_rename_gateway_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='members',
            field=models.ManyToManyField(related_name='agencies', through='social_stats.AgencyMembership', through_fields=('agency', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
