# Generated by Django 5.2.17 on 2026-09-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_stats", "0065_alter_agency_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarpost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="clientgoal",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                    ("all", "All Platforms"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="competitorsnapshot",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dailymetric",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="platformcredential",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="platformpublishlog",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="postingschedule",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="postmetric",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="unifiedreview",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                default="google_my_business",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="weeklytoppost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("google_my_business", "Google My Business"),
                    ("telegram", "Telegram"),
                    ("bale", "Bale"),
                    ("eitaa", "Eitaa"),
                    ("aparat", "Aparat"),
                ],
                max_length=30,
            ),
        ),
    ]
