# Generated by Django 5.2.17 on 2026-10-02 06:25

import django.db.models.deletion
from django.db import migrations, models


def populate_social_accounts(apps, schema_editor):
    """Keep history unassigned: current credentials cannot prove past ownership.

    External identity must be independently reconciled before historical rows
    can be attached to an account. This also covers removed credentials.
    """
    pass


def prevent_unsafe_reverse(apps, schema_editor):
    """Require data reconciliation before restoring platform-wide uniqueness."""
    from django.db.migrations.exceptions import IrreversibleError
    raise IrreversibleError(
        "Account-scoped data requires reconciliation before rollback; "
        "restore a pre-upgrade backup or roll forward instead."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("social_stats", "0067_socialaccount_multi_account"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="dailymetric",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="postmetric",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="unifiedreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="conversation",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="dailymetric",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="platformpublishlog",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publish_logs",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="postmetric",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_metrics",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sync_logs",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="unifiedreview",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.RunPython(populate_social_accounts, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={
                ("client", "platform", "social_account", "platform_thread_id")
            },
        ),
        migrations.AlterUniqueTogether(
            name="dailymetric",
            unique_together={("client", "platform", "social_account", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="postmetric",
            unique_together={("client", "platform", "social_account", "post_id")},
        ),
        migrations.AlterUniqueTogether(
            name="unifiedreview",
            unique_together={
                ("client", "platform", "social_account", "platform_review_id")
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, prevent_unsafe_reverse),
    ]
