# Generated by Django 5.2.17 on 2026-10-02 06:25

import django.db.models.deletion
from django.db import migrations, models


def populate_social_accounts(apps, schema_editor):
    PlatformCredential = apps.get_model("social_stats", "PlatformCredential")
    account_by_scope = {}
    ambiguous = set()
    for client_id, platform, account_id in PlatformCredential.objects.exclude(
        social_account_id=None
    ).values_list("client_id", "platform", "social_account_id"):
        key = (client_id, platform)
        if key in account_by_scope and account_by_scope[key] != account_id:
            ambiguous.add(key)
        else:
            account_by_scope[key] = account_id

    # Historical rows can only be attributed safely when the workspace had one
    # account for that platform. Ambiguous rows deliberately remain unassigned.
    for model_name in ("DailyMetric", "PostMetric", "SyncLog", "Conversation", "UnifiedReview"):
        Model = apps.get_model("social_stats", model_name)
        for (client_id, platform), account_id in account_by_scope.items():
            if (client_id, platform) not in ambiguous:
                Model.objects.filter(
                    client_id=client_id, platform=platform, social_account_id=None,
                ).update(social_account_id=account_id)

    PublishLog = apps.get_model("social_stats", "PlatformPublishLog")
    for log in PublishLog.objects.filter(social_account_id=None).iterator():
        key = (log.unified_post.client_id, log.platform)
        if key in account_by_scope and key not in ambiguous:
            log.social_account_id = account_by_scope[key]
            log.save(update_fields=["social_account"])


class Migration(migrations.Migration):

    dependencies = [
        ("social_stats", "0067_socialaccount_multi_account"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="dailymetric",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="postmetric",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="unifiedreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="conversation",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="dailymetric",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="platformpublishlog",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publish_logs",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="postmetric",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_metrics",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sync_logs",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.AddField(
            model_name="unifiedreview",
            name="social_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="social_stats.socialaccount",
            ),
        ),
        migrations.RunPython(populate_social_accounts, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={
                ("client", "platform", "social_account", "platform_thread_id")
            },
        ),
        migrations.AlterUniqueTogether(
            name="dailymetric",
            unique_together={("client", "platform", "social_account", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="postmetric",
            unique_together={("client", "platform", "social_account", "post_id")},
        ),
        migrations.AlterUniqueTogether(
            name="unifiedreview",
            unique_together={
                ("client", "platform", "social_account", "platform_review_id")
            },
        ),
    ]
