# Generated by Django 5.2.17 on 2026-10-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0068_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company'], 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('client', 'Workspace member')], default='client', max_length=20),
        ),
    ]
