# Generated by Django 5.2.17 on 2026-10-02 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_stats", "0071_seed_role_presets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unifiedpost",
            name="publish_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_post_publications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
