# Generated by Django 5.2.17 on 2026-10-02 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_stats", "0072_unifiedpost_publish_requested_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="queueditem",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_queue_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unifiedpost",
            name="publish_action",
            field=models.CharField(
                choices=[("publish_posts", "Publish"), ("schedule_posts", "Schedule")],
                default="publish_posts",
                max_length=20,
            ),
        ),
    ]
