# Generated by Django 5.2.17 on 2026-10-03 05:24

import django.db.models.deletion
import social_stats.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0073_queueditem_requested_by_unifiedpost_publish_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'قانون خودکارسازی', 'verbose_name_plural': 'قانون‌های خودکارسازی'},
        ),
        migrations.AlterModelOptions(
            name='calendarnote',
            options={'ordering': ['date', 'id'], 'verbose_name': 'یادداشت تقویم', 'verbose_name_plural': 'یادداشت‌های تقویم'},
        ),
        migrations.AlterModelOptions(
            name='calendarpost',
            options={'ordering': ['-scheduled_at', '-published_at'], 'verbose_name': 'پست تقویم محتوا', 'verbose_name_plural': 'پست‌های تقویم محتوا'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company'], 'verbose_name': 'فضای کاری', 'verbose_name_plural': 'فضاهای کاری'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at'], 'verbose_name': 'گفتگو', 'verbose_name_plural': 'گفتگوها'},
        ),
        migrations.AlterModelOptions(
            name='dailymetric',
            options={'ordering': ['-date'], 'verbose_name': 'آمار روزانه', 'verbose_name_plural': 'آمارهای روزانه'},
        ),
        migrations.AlterModelOptions(
            name='lookupcollection',
            options={'ordering': ['key'], 'verbose_name': 'مجموعه داده مرجع', 'verbose_name_plural': 'مجموعه‌های داده مرجع'},
        ),
        migrations.AlterModelOptions(
            name='lookupitem',
            options={'ordering': ['collection__key', 'sort_order', 'label'], 'verbose_name': 'گزینه داده مرجع', 'verbose_name_plural': 'گزینه‌های داده مرجع'},
        ),
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل رسانه‌ای', 'verbose_name_plural': 'فایل‌های رسانه‌ای'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at', 'id'], 'verbose_name': 'پیام', 'verbose_name_plural': 'پیام‌ها'},
        ),
        migrations.AlterModelOptions(
            name='platformcredential',
            options={'ordering': ['platform'], 'verbose_name': 'اطلاعات اتصال پلتفرم', 'verbose_name_plural': 'اطلاعات اتصال پلتفرم‌ها'},
        ),
        migrations.AlterModelOptions(
            name='platformpublishlog',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'گزارش انتشار پلتفرم', 'verbose_name_plural': 'گزارش‌های انتشار پلتفرم‌ها'},
        ),
        migrations.AlterModelOptions(
            name='postingschedule',
            options={'ordering': ['platform', 'day_of_week', 'hour'], 'verbose_name': 'زمان‌بندی انتشار', 'verbose_name_plural': 'زمان‌بندی‌های انتشار'},
        ),
        migrations.AlterModelOptions(
            name='postqueue',
            options={'ordering': ['-created_at'], 'verbose_name': 'صف انتشار', 'verbose_name_plural': 'صف‌های انتشار'},
        ),
        migrations.AlterModelOptions(
            name='queueditem',
            options={'ordering': ['queue', 'sort_order', 'id'], 'verbose_name': 'آیتم صف انتشار', 'verbose_name_plural': 'آیتم‌های صف انتشار'},
        ),
        migrations.AlterModelOptions(
            name='roireport',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'گزارش بازگشت سرمایه', 'verbose_name_plural': 'گزارش‌های بازگشت سرمایه'},
        ),
        migrations.AlterModelOptions(
            name='roisettings',
            options={'verbose_name': 'تنظیمات بازگشت سرمایه', 'verbose_name_plural': 'تنظیمات بازگشت سرمایه'},
        ),
        migrations.AlterModelOptions(
            name='rolepreset',
            options={'verbose_name': 'الگوی نقش', 'verbose_name_plural': 'الگوهای نقش'},
        ),
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'ordering': ['key'], 'verbose_name': 'محتوای سایت', 'verbose_name_plural': 'محتواهای سایت'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['platform', 'display_name', 'id'], 'verbose_name': 'حساب شبکه اجتماعی', 'verbose_name_plural': 'حساب‌های شبکه‌های اجتماعی'},
        ),
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ['-started_at'], 'verbose_name': 'گزارش همگام‌سازی', 'verbose_name_plural': 'گزارش‌های همگام‌سازی'},
        ),
        migrations.AlterModelOptions(
            name='unifiedpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'پست یکپارچه', 'verbose_name_plural': 'پست‌های یکپارچه'},
        ),
        migrations.AlterModelOptions(
            name='unifiedreview',
            options={'ordering': ['-created_at_platform'], 'verbose_name': 'نظر مشتری', 'verbose_name_plural': 'نظرهای مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل‌های کاربران'},
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='تنظیمات عملیات'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_type',
            field=models.CharField(choices=[('auto_reply', 'پاسخ خودکار'), ('ai_smart_reply', 'پاسخ هوشمند با هوش مصنوعی'), ('notify', 'ارسال اعلان'), ('assign', 'تخصیص به کاربر'), ('add_tag', 'افزودن برچسب'), ('webhook', 'فراخوانی وب‌هوک')], max_length=40, verbose_name='نوع عملیات'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین اجرا'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='run_count',
            field=models.IntegerField(default=0, verbose_name='تعداد اجرا'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_filters',
            field=models.JSONField(blank=True, default=dict, help_text='شرط‌ها در قالب JSON با کلیدهایی مانند platforms، keywords و sentiment.', verbose_name='شرط‌های محرک'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('new_comment', 'دیدگاه جدید'), ('new_dm', 'پیام مستقیم جدید'), ('new_review', 'نظر جدید مشتری'), ('keyword_mention', 'اشاره به کلیدواژه'), ('negative_sentiment', 'تشخیص احساس منفی'), ('viral_post', 'افزایش سریع بازدید پست'), ('new_follower', 'دنبال‌کننده جدید')], max_length=40, verbose_name='نوع محرک'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notes', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='color',
            field=models.CharField(default='#2563EB', max_length=7, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_notes', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='is_client_visible',
            field=models.BooleanField(default=False, verbose_name='قابل مشاهده برای اعضای فضای کاری'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='note',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='calendarnote',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='caption',
            field=models.TextField(blank=True, verbose_name='متن کپشن'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_posts', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='comments',
            field=models.BigIntegerField(default=0, verbose_name='تعداد دیدگاه'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_posts', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='نرخ تعامل (درصد)'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='external_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='شناسه در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='hashtags',
            field=models.TextField(blank=True, verbose_name='هشتگ‌ها'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='impressions',
            field=models.BigIntegerField(default=0, verbose_name='تعداد نمایش'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='likes',
            field=models.BigIntegerField(default=0, verbose_name='تعداد پسندیدن'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='media_url',
            field=models.URLField(blank=True, verbose_name='نشانی رسانه'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت‌ها'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='post_metric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_post', to='social_stats.postmetric', verbose_name='آمار پست'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='post_type',
            field=models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو'), ('reel', 'ریل'), ('story', 'استوری'), ('carousel', 'چنداسلایدی'), ('text', 'متن'), ('article', 'مقاله'), ('short', 'ویدئوی کوتاه')], default='image', max_length=20, verbose_name='نوع پست'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='post_url',
            field=models.URLField(blank=True, verbose_name='نشانی پست'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='reach',
            field=models.BigIntegerField(default=0, verbose_name='دسترسی (تعداد مخاطبان یکتا)'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='saves',
            field=models.BigIntegerField(default=0, verbose_name='تعداد ذخیره'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار برنامه‌ریزی‌شده'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='shares',
            field=models.BigIntegerField(default=0, verbose_name='تعداد اشتراک‌گذاری'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='status',
            field=models.CharField(choices=[('published', 'منتشر شده'), ('scheduled', 'زمان‌بندی شده'), ('draft', 'پیش‌نویس'), ('failed', 'ناموفق')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='calendarpost',
            name='video_views',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازدید ویدئو'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bot_enabled',
            field=models.BooleanField(default=True, verbose_name='ربات فعال'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bot_max_msgs_per_conv',
            field=models.IntegerField(default=200, verbose_name='حداکثر پیام ربات در هر گفتگو'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bot_max_msgs_per_minute',
            field=models.IntegerField(default=20, verbose_name='حداکثر پیام ربات به هر مخاطب در دقیقه'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bot_spam_threshold',
            field=models.IntegerField(default=5, verbose_name='آستانه امتیاز هرزنامه'),
        ),
        migrations.AlterField(
            model_name='client',
            name='brand_assets',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات دارایی‌های برند در قالب JSON، مانند نشانی لوگو و اطلاعات تماس.', verbose_name='دارایی‌های برند'),
        ),
        migrations.AlterField(
            model_name='client',
            name='brand_description',
            field=models.TextField(blank=True, verbose_name='توضیحات برند'),
        ),
        migrations.AlterField(
            model_name='client',
            name='brand_tone',
            field=models.CharField(blank=True, choices=[('professional', 'حرفه‌ای'), ('casual', 'خودمانی'), ('funny', 'طنز'), ('inspirational', 'الهام‌بخش'), ('urgent', 'فوری'), ('friendly', 'دوستانه')], max_length=50, verbose_name='لحن برند'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_category',
            field=models.CharField(blank=True, help_text='برای مثال: فروشگاه، خدمات یا صنایع الکترونیک.', max_length=100, verbose_name='دسته کسب‌وکار'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='موقعیت کسب‌وکار'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_subcategories',
            field=models.JSONField(blank=True, default=list, help_text='فهرست زیر‌دسته‌ها در قالب JSON؛ برای مثال: ["پوشاک", "کفش"].', verbose_name='زیر‌دسته‌های کسب‌وکار'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=200, verbose_name='نام کسب‌وکار'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_via',
            field=models.CharField(choices=[('end_user_signup', 'ثبت‌نام مستقیم کاربر'), ('agency_invite', 'ایجاد توسط آژانس'), ('marketplace', 'اتصال از بازار خدمات')], default='agency_invite', max_length=20, verbose_name='روش ایجاد'),
        ),
        migrations.AlterField(
            model_name='client',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام نمایشی'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='features_enabled',
            field=models.JSONField(blank=True, default=dict, help_text='مجوز قابلیت‌ها در قالب JSON؛ برای مثال: {"composer": true, "scheduler": true}.', verbose_name='قابلیت‌های فعال'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('all', 'همه'), ('male', 'مرد'), ('female', 'زن'), ('non_binary', 'غیردودویی'), ('unspecified', 'مشخص نشده')], max_length=20, verbose_name='جنسیت مخاطبان'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gmb_url',
            field=models.URLField(blank=True, help_text='نشانی پروفایل کسب‌وکار در گوگل.', verbose_name='نشانی پروفایل کسب‌وکار در گوگل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=50, verbose_name='حوزه فعالیت'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_discoverable_in_marketplace',
            field=models.BooleanField(default=False, verbose_name='قابل نمایش در بازار خدمات'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_processing_paused',
            field=models.BooleanField(default=False, help_text='با فعال شدن، همگام‌سازی، درخواست‌های هوش مصنوعی و ایجاد یا انتشار پست متوقف می‌شود.', verbose_name='پردازش داده‌ها متوقف شده'),
        ),
        migrations.AlterField(
            model_name='client',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='client',
            name='location_country',
            field=models.CharField(blank=True, help_text='کد دوحرفی کشور؛ برای مثال: IR.', max_length=2, verbose_name='کد کشور'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='client',
            name='meta_capi_test_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='کد آزمایش API تبدیل متا'),
        ),
        migrations.AlterField(
            model_name='client',
            name='meta_pixel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='شناسه پیکسل متا'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام مسئول تماس'),
        ),
        migrations.AlterField(
            model_name='client',
            name='onboarding_complete',
            field=models.BooleanField(default=False, verbose_name='راه‌اندازی اولیه تکمیل شده'),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مالک'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ownership_type',
            field=models.CharField(choices=[('end_user_owned', 'متعلق به کاربر نهایی'), ('agency_owned', 'متعلق به آژانس'), ('orphaned', 'بدون مالک')], default='agency_owned', max_length=20, verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='client',
            name='product_images',
            field=models.JSONField(blank=True, default=list, help_text='فهرست نشانی تصاویر محصولات در قالب JSON.', verbose_name='تصاویر محصولات'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='انتشار نیازمند تأیید'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'رایگان'), ('pro', 'حرفه‌ای'), ('premium', 'ویژه'), ('agency_managed', 'مدیریت‌شده توسط آژانس')], default='free', max_length=20, verbose_name='طرح اشتراک'),
        ),
        migrations.AlterField(
            model_name='client',
            name='target_audience',
            field=models.TextField(blank=True, verbose_name='مخاطبان هدف'),
        ),
        migrations.AlterField(
            model_name='client',
            name='target_locations',
            field=models.JSONField(blank=True, default=list, help_text='فهرست کشورها یا شهرهای هدف در قالب JSON.', verbose_name='موقعیت‌های جغرافیایی هدف'),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='نام استاندارد منطقه زمانی؛ برای مثال: Asia/Tehran.', max_length=64, verbose_name='منطقه زمانی'),
        ),
        migrations.AlterField(
            model_name='client',
            name='usp',
            field=models.TextField(blank=True, help_text='ویژگی‌هایی که برند را از رقبا متمایز می‌کنند.', verbose_name='مزیت‌های رقابتی برند'),
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, verbose_name='نشانی وب‌سایت'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='واتس‌اپ فعال'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='شماره واتس‌اپ'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='مسئول رسیدگی'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact_avatar_url',
            field=models.URLField(blank=True, verbose_name='نشانی تصویر مخاطب'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact_handle',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام کاربری مخاطب'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام مخاطب'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی شده'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='رسیدگی شده'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_starred',
            field=models.BooleanField(default=False, verbose_name='ستاره‌دار'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین پیام'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_preview',
            field=models.CharField(blank=True, max_length=500, verbose_name='پیش‌نمایش آخرین پیام'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_outbound_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین پیام ارسالی'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='linked_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_conversations', to='social_stats.botflow', verbose_name='جریان ربات مرتبط'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='linked_publish_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='social_stats.platformpublishlog', verbose_name='گزارش انتشار مرتبط'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='platform_thread_id',
            field=models.CharField(db_index=True, max_length=300, verbose_name='شناسه گفتگو در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'مثبت'), ('neutral', 'خنثی'), ('negative', 'منفی'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='احساس متن'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='social_stats.socialaccount', verbose_name='حساب شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='برچسب‌ها'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('comment', 'دیدگاه'), ('dm', 'پیام مستقیم'), ('mention', 'اشاره به حساب'), ('review', 'نظر مشتری')], default='comment', max_length=20, verbose_name='نوع گفتگو'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='unread_count',
            field=models.IntegerField(default=0, verbose_name='تعداد پیام‌های خوانده‌نشده'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='accounts_engaged',
            field=models.BigIntegerField(default=0, verbose_name='تعداد حساب‌های تعامل‌کننده'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='avg_view_duration',
            field=models.FloatField(default=0, verbose_name='میانگین مدت تماشا (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='business_conversations',
            field=models.BigIntegerField(default=0, verbose_name='تعداد گفتگوهای کسب‌وکار'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='clicks',
            field=models.BigIntegerField(default=0, verbose_name='تعداد کلیک'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='comments',
            field=models.BigIntegerField(default=0, verbose_name='تعداد دیدگاه'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='ctr',
            field=models.FloatField(default=0, verbose_name='نرخ کلیک (درصد)'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='direction_clicks',
            field=models.BigIntegerField(default=0, verbose_name='تعداد کلیک دکمه مسیریابی'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='direction_requests',
            field=models.BigIntegerField(default=0, verbose_name='تعداد درخواست مسیریابی'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='email_contacts',
            field=models.BigIntegerField(default=0, verbose_name='تعداد کلیک دکمه ایمیل'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='engagement_rate',
            field=models.FloatField(default=0, verbose_name='نرخ تعامل (درصد)'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='fb_video_views',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازدید ویدئوی فیسبوک'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='fb_video_watch_time',
            field=models.BigIntegerField(default=0, verbose_name='مدت تماشای ویدئوی فیسبوک (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='followers',
            field=models.BigIntegerField(default=0, verbose_name='تعداد دنبال‌کنندگان'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='followers_lost',
            field=models.BigIntegerField(default=0, verbose_name='تعداد دنبال‌کنندگان ازدست‌رفته فیسبوک'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='ig_followers_lost',
            field=models.BigIntegerField(default=0, verbose_name='تعداد دنبال‌کنندگان ازدست‌رفته اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='impressions',
            field=models.BigIntegerField(default=0, verbose_name='تعداد نمایش'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='likes',
            field=models.BigIntegerField(default=0, verbose_name='تعداد پسندیدن'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='maps_impressions',
            field=models.BigIntegerField(default=0, verbose_name='تعداد نمایش در نقشه گوگل'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='negative_feedback',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازخوردهای منفی'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='page_views',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازدید صفحه'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='phone_call_clicks',
            field=models.BigIntegerField(default=0, verbose_name='تعداد کلیک دکمه تماس'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='phone_calls',
            field=models.BigIntegerField(default=0, verbose_name='تعداد تماس تلفنی'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='photo_views',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازدید تصاویر'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='profile_views',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازدید پروفایل'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='reach',
            field=models.BigIntegerField(default=0, verbose_name='دسترسی (تعداد مخاطبان یکتا)'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, verbose_name='واکنش‌ها'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='saves',
            field=models.BigIntegerField(default=0, verbose_name='تعداد ذخیره'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='search_impressions',
            field=models.BigIntegerField(default=0, verbose_name='تعداد نمایش در جستجوی گوگل'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='sessions',
            field=models.BigIntegerField(default=0, verbose_name='تعداد نشست وب‌سایت'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='shares',
            field=models.BigIntegerField(default=0, verbose_name='تعداد اشتراک‌گذاری'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='social_stats.socialaccount', verbose_name='حساب شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='subscribers_lost',
            field=models.BigIntegerField(default=0, verbose_name='تعداد مشترکان ازدست‌رفته'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان همگام‌سازی'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='total_interactions',
            field=models.BigIntegerField(default=0, verbose_name='مجموع تعاملات'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='users',
            field=models.BigIntegerField(default=0, verbose_name='تعداد کاربران وب‌سایت'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='video_views',
            field=models.BigIntegerField(default=0, verbose_name='تعداد بازدید ویدئو'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='watch_time_minutes',
            field=models.BigIntegerField(default=0, verbose_name='مدت تماشای ویدئو (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='dailymetric',
            name='website_clicks',
            field=models.BigIntegerField(default=0, verbose_name='تعداد کلیک وب‌سایت'),
        ),
        migrations.AlterField(
            model_name='lookupcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='lookupcollection',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='عمومی'),
        ),
        migrations.AlterField(
            model_name='lookupcollection',
            name='key',
            field=models.SlugField(max_length=120, unique=True, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='lookupcollection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='lookupcollection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='social_stats.lookupcollection', verbose_name='مجموعه داده مرجع'),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='key',
            field=models.CharField(max_length=120, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='label',
            field=models.CharField(max_length=255, verbose_name='عنوان نمایشی'),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='parent_key',
            field=models.CharField(blank=True, max_length=120, verbose_name='کلید والد'),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='alt_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='duration_seconds',
            field=models.FloatField(default=0, verbose_name='مدت رسانه (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(upload_to='media_assets/%Y/%m/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='حجم فایل (بایت)'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='folder',
            field=models.CharField(blank=True, max_length=100, verbose_name='پوشه'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='height',
            field=models.IntegerField(default=0, verbose_name='ارتفاع (پیکسل)'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع فایل (MIME)'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='برچسب‌ها'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media_assets/thumbs/%Y/%m/', verbose_name='تصویر بندانگشتی'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری‌کننده'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='width',
            field=models.IntegerField(default=0, verbose_name='عرض (پیکسل)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_suggested_reply',
            field=models.TextField(blank=True, verbose_name='پاسخ پیشنهادی هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author_avatar_url',
            field=models.URLField(blank=True, verbose_name='نشانی تصویر نویسنده'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author_handle',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام کاربری نویسنده'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام نویسنده'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_stats.conversation', verbose_name='گفتگو'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('inbound', 'دریافتی'), ('outbound', 'ارسالی')], default='inbound', max_length=10, verbose_name='جهت پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='linked_bot_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='social_stats.botconversationstep', verbose_name='مرحله مرتبط ربات'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_urls',
            field=models.JSONField(blank=True, default=list, verbose_name='نشانی‌های رسانه'),
        ),
        migrations.AlterField(
            model_name='message',
            name='platform_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='شناسه پیام در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='کاربری که پاسخ خروجی را نوشته است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='ارسال‌کننده'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'مثبت'), ('neutral', 'خنثی'), ('negative', 'منفی'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='احساس متن'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='access_token',
            field=social_stats.fields.EncryptedTextField(blank=True, verbose_name='توکن دسترسی'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='auth_method',
            field=models.CharField(choices=[('oauth', 'احراز هویت OAuth'), ('manual_token', 'توکن دستی'), ('system_user', 'کاربر سیستمی')], default='oauth', max_length=20, verbose_name='روش احراز هویت'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='channel_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='شناسه کانال یوتیوب'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام کانال یوتیوب'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان اتصال'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='gmb_account_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='شناسه حساب کسب‌وکار گوگل'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='gmb_location_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='شناسه موقعیت کسب‌وکار گوگل'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='instagram_account_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='شناسه حساب اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='organization_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='شناسه سازمان لینکدین'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام سازمان لینکدین'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='page_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='شناسه صفحه فیسبوک'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='page_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام صفحه فیسبوک'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='platform_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='شناسه کاربر در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='refresh_token',
            field=social_stats.fields.EncryptedTextField(blank=True, verbose_name='توکن تمدید دسترسی'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='scope',
            field=models.TextField(blank=True, verbose_name='دامنه دسترسی'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='social_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='social_stats.socialaccount', verbose_name='حساب شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='token_type',
            field=models.CharField(blank=True, default='Bearer', max_length=50, verbose_name='نوع توکن'),
        ),
        migrations.AlterField(
            model_name='platformcredential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تلاش برای انتشار'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='engagement_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان همگام‌سازی تعاملات'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='error_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='کد خطا'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='شرح خطا'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='platform_post_id',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='شناسه پست در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='platform_url',
            field=models.URLField(blank=True, verbose_name='نشانی پست در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='پاسخ خام پلتفرم'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_logs', to='social_stats.socialaccount', verbose_name='حساب شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('publishing', 'در حال انتشار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('skipped', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='platformpublishlog',
            name='unified_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to='social_stats.unifiedpost', verbose_name='پست یکپارچه'),
        ),
        migrations.AlterField(
            model_name='postingschedule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedules', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='postingschedule',
            name='day_of_week',
            field=models.IntegerField(help_text='شماره روز هفته: دوشنبه ۰، سه‌شنبه ۱، چهارشنبه ۲، پنجشنبه ۳، جمعه ۴، شنبه ۵، یکشنبه ۶.', verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='postingschedule',
            name='hour',
            field=models.IntegerField(verbose_name='ساعت'),
        ),
        migrations.AlterField(
            model_name='postingschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='postingschedule',
            name='minute',
            field=models.IntegerField(default=0, verbose_name='دقیقه'),
        ),
        migrations.AlterField(
            model_name='postingschedule',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='postingschedule',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_queues', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='last_dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین ارسال از صف'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='platforms',
            field=models.JSONField(blank=True, default=list, verbose_name='پلتفرم‌ها'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='queue_strategy',
            field=models.CharField(choices=[('round_robin', 'چرخشی'), ('random', 'تصادفی'), ('sequential', 'به‌ترتیب')], default='sequential', max_length=20, verbose_name='روش انتخاب از صف'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='schedule_rule',
            field=models.CharField(blank=True, help_text='قاعده زمان‌بندی مطابق RFC 5545 (RRULE) یا عبارت cron.', max_length=500, verbose_name='قاعده زمان‌بندی'),
        ),
        migrations.AlterField(
            model_name='postqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='content',
            field=models.TextField(blank=True, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, verbose_name='هشتگ‌ها'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='media_urls',
            field=models.JSONField(blank=True, default=list, verbose_name='نشانی‌های رسانه'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='social_stats.postqueue', verbose_name='صف انتشار'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_queue_items', to=settings.AUTH_USER_MODEL, verbose_name='درخواست‌کننده'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار استفاده'), ('used', 'استفاده شده'), ('skipped', 'رد شده')], default='waiting', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='unified_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_queue_item', to='social_stats.unifiedpost', verbose_name='پست یکپارچه'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='agency_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حق‌الزحمه آژانس'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_reports', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='cost_per_click',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='هزینه هر کلیک'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='cost_per_lead',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='هزینه هر سرنخ'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='cost_per_sale',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='هزینه هر فروش'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='estimated_leads',
            field=models.IntegerField(default=0, verbose_name='تعداد سرنخ تخمینی'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='estimated_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='درآمد تخمینی'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='estimated_sales',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش تخمینی'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید گزارش'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='month',
            field=models.IntegerField(verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='platform_breakdown',
            field=models.JSONField(default=dict, verbose_name='تفکیک آمار پلتفرم‌ها'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بازگشت سرمایه (درصد)'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='total_clicks',
            field=models.BigIntegerField(default=0, verbose_name='مجموع کلیک‌ها'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='total_impressions',
            field=models.BigIntegerField(default=0, verbose_name='مجموع نمایش‌ها'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع سرمایه‌گذاری'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='total_reach',
            field=models.BigIntegerField(default=0, verbose_name='مجموع دسترسی مخاطبان'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='website_clicks',
            field=models.BigIntegerField(default=0, verbose_name='تعداد کلیک وب‌سایت'),
        ),
        migrations.AlterField(
            model_name='roireport',
            name='year',
            field=models.IntegerField(verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='agency_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حق‌الزحمه آژانس'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='avg_sale_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='میانگین ارزش هر فروش'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roi_settings', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='نرخ تبدیل کلیک به سرنخ (درصد)'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='کد ارز'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5, verbose_name='نماد ارز'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='facebook_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بودجه فیسبوک'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='gmb_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بودجه کسب‌وکار گوگل'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='instagram_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بودجه اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='lead_to_sale_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='نرخ تبدیل سرنخ به فروش (درصد)'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='linkedin_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بودجه لینکدین'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='monthly_leads_goal',
            field=models.IntegerField(default=0, verbose_name='هدف تعداد سرنخ ماهانه'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='monthly_revenue_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هدف درآمد ماهانه'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='roisettings',
            name='youtube_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بودجه یوتیوب'),
        ),
        migrations.AlterField(
            model_name='rolepreset',
            name='approval_defaults',
            field=models.JSONField(blank=True, default=dict, verbose_name='تنظیمات پیش‌فرض تأیید'),
        ),
        migrations.AlterField(
            model_name='rolepreset',
            name='key',
            field=models.SlugField(unique=True, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='rolepreset',
            name='label',
            field=models.CharField(max_length=100, verbose_name='عنوان نمایشی'),
        ),
        migrations.AlterField(
            model_name='rolepreset',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='مجوزهای دسترسی'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اجرا'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='عمومی'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='key',
            field=models.SlugField(max_length=120, unique=True, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین بازنگری'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='نشانی تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام نمایشی'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='external_id',
            field=models.CharField(max_length=200, verbose_name='شناسه در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='شرح خطا'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='records_synced',
            field=models.IntegerField(default=0, verbose_name='تعداد رکوردهای همگام‌شده'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='social_stats.socialaccount', verbose_name='حساب شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='ai_generated',
            field=models.BooleanField(default=False, verbose_name='تولیدشده با هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='ai_prompt',
            field=models.TextField(blank=True, verbose_name='دستور هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_unified_posts', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_posts', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='content',
            field=models.TextField(blank=True, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unified_posts', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='انتشار تکرارشونده'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='media_assets',
            field=models.ManyToManyField(blank=True, related_name='used_in_posts', to='social_stats.mediaasset', verbose_name='فایل‌های رسانه‌ای'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='media_type',
            field=models.CharField(choices=[('text', 'فقط متن'), ('image', 'تصویر'), ('video', 'ویدئو'), ('carousel', 'چنداسلایدی'), ('reel', 'ریل'), ('story', 'استوری')], default='text', max_length=20, verbose_name='نوع رسانه'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='media_urls',
            field=models.JSONField(blank=True, default=list, help_text='فهرست مرتب‌شده نشانی رسانه‌ها در قالب JSON.', verbose_name='نشانی‌های رسانه'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='platform_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='تنظیمات اختصاصی با ساختار {"platform": {"content": "...", "media_urls": [], "hashtags": []}}.', verbose_name='تنظیمات اختصاصی هر پلتفرم'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='publish_action',
            field=models.CharField(choices=[('publish_posts', 'انتشار'), ('schedule_posts', 'زمان‌بندی')], default='publish_posts', max_length=20, verbose_name='نوع درخواست انتشار'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='publish_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_post_publications', to=settings.AUTH_USER_MODEL, verbose_name='درخواست‌کننده انتشار'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text='قاعده تکرار مطابق استاندارد RFC 5545 (RRULE).', max_length=500, verbose_name='قاعده تکرار انتشار'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار برنامه‌ریزی‌شده'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش‌نویس'), ('pending_approval', 'در انتظار تأیید'), ('scheduled', 'زمان‌بندی شده'), ('queued', 'در صف انتشار'), ('publishing', 'در حال انتشار'), ('published', 'منتشر شده'), ('partial', 'انتشار ناقص'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='target_platforms',
            field=models.JSONField(blank=True, default=list, help_text='فهرست کلید پلتفرم‌های مقصد در قالب JSON؛ برای مثال: ["instagram", "telegram"].', verbose_name='پلتفرم‌های مقصد'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='title',
            field=models.CharField(blank=True, help_text='عنوان داخلی اختیاری برای شناسایی پست.', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_reviews', to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='created_at_platform',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='language',
            field=models.CharField(blank=True, max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa'), ('youtube', 'YouTube'), ('aparat', 'Aparat'), ('google_my_business', 'Google Business Profile'), ('neshan', 'Neshan')], default='google_my_business', max_length=30, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='platform_review_id',
            field=models.CharField(db_index=True, max_length=300, verbose_name='شناسه نظر در پلتفرم'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_reviews', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ‌دهنده'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='reply_text',
            field=models.TextField(blank=True, verbose_name='متن پاسخ'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='reviewer_avatar_url',
            field=models.URLField(blank=True, verbose_name='نشانی تصویر ثبت‌کننده نظر'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام ثبت‌کننده نظر'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'مثبت'), ('neutral', 'خنثی'), ('negative', 'منفی'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='احساس متن'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='social_stats.socialaccount', verbose_name='حساب شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('replied', 'پاسخ داده شده'), ('flagged', 'علامت‌گذاری شده')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='unifiedreview',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان همگام‌سازی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('end_user', 'کاربر نهایی'), ('agency_member', 'عضو آژانس'), ('legacy', 'حساب قدیمی')], default='legacy', max_length=20, verbose_name='نوع حساب'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مدیر آژانس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, related_name='staff_assigned', to='social_stats.client', verbose_name='فضاهای کاری تخصیص‌یافته'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر کاربر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_stats.client', verbose_name='فضای کاری'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='social_stats.client', verbose_name='فضای کاری پیش‌فرض'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=True, verbose_name='ایمیل تأیید شده'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_self_registered',
            field=models.BooleanField(default=False, verbose_name='ثبت‌نام توسط خود کاربر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='social_stats.agency', verbose_name='آژانس اصلی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'مدیر کل'), ('staff', 'کارمند'), ('client', 'عضو فضای کاری')], default='client', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='شرایط استفاده پذیرفته شده'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پذیرش شرایط استفاده'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
