# Generated by Django 5.2.17 on 2026-10-03 15:57

import django.db.models.deletion
import social_stats.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0074_persian_admin_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queueditem',
            name='media_type',
            field=models.CharField(blank=True, choices=[('album', 'آلبوم تلگرام'), ('rich', 'مقاله غنی تلگرام'), ('poll', 'نظرسنجی تلگرام'), ('text', 'فقط متن'), ('image', 'تصویر'), ('video', 'ویدئو'), ('carousel', 'چنداسلایدی'), ('reel', 'ریل'), ('story', 'استوری')], max_length=20, verbose_name='نوع رسانه'),
        ),
        migrations.AddField(
            model_name='queueditem',
            name='platform_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='تنظیمات اختصاصی پلتفرم'),
        ),
        migrations.AlterField(
            model_name='unifiedpost',
            name='media_type',
            field=models.CharField(choices=[('album', 'آلبوم تلگرام'), ('rich', 'مقاله غنی تلگرام'), ('poll', 'نظرسنجی تلگرام'), ('text', 'فقط متن'), ('image', 'تصویر'), ('video', 'ویدئو'), ('carousel', 'چنداسلایدی'), ('reel', 'ریل'), ('story', 'استوری')], default='text', max_length=20, verbose_name='نوع رسانه'),
        ),
        migrations.CreateModel(
            name='TelegramCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('chat_id', models.CharField(max_length=80)),
                ('action', models.CharField(default='acknowledge', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_stats.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_secret', social_stats.fields.EncryptedTextField(blank=True)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('destination_context', models.JSONField(blank=True, default=dict)),
                ('assistant_enabled', models.BooleanField(default=False)),
                ('rich_enabled', models.BooleanField(default=True)),
                ('assistant_rich', models.BooleanField(default=False)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('replay_floor', models.BigIntegerField(default=-1)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to='social_stats.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_stats.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAssistantRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('draft_id', models.PositiveIntegerField()),
                ('state', models.CharField(default='pending', max_length=20)),
                ('cancelled', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_stats.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_update', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_stats.telegramupdate')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAssistantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_stats.socialaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'telegram_user_id'), name='telegram_unique_identity_link')],
            },
        ),
        migrations.CreateModel(
            name='TelegramSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('content', models.TextField(blank=True)),
                ('media', models.JSONField(default=dict)),
                ('proposal', models.JSONField(default=dict)),
                ('provider_update_id', models.BigIntegerField(default=-1)),
                ('provider_state', models.CharField(default='pending', max_length=30)),
                ('state', models.CharField(default='received', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_stats.socialaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_stats.client')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_stats.conversation')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_stats.unifiedpost')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'conversation', 'message_id'), name='telegram_unique_suggestion')],
            },
        ),
        migrations.AddConstraint(
            model_name='telegramupdate',
            constraint=models.UniqueConstraint(fields=('account', 'update_id'), name='telegram_unique_update'),
        ),
    ]
