# Generated by Django 5.2.17 on 2026-10-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_organizations(apps, schema_editor):
    Workspace = apps.get_model('social_stats', 'Client')
    Organization = apps.get_model('social_stats', 'Organization')
    using = schema_editor.connection.alias
    for workspace in Workspace.objects.using(using).filter(
        organization_id__isnull=True
    ).iterator(chunk_size=1000):
        organization = Organization.objects.using(using).create(
            name=workspace.company,
            owner_user_id=workspace.owner_user_id,
        )
        Workspace.objects.using(using).filter(pk=workspace.pk).update(
            organization_id=organization.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0075_telegram_advanced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('requires_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='social_stats.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='social_stats.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_membership')],
            },
        ),
        # One tenant per historical workspace, without inferred memberships.
        # Reversal would discard tenant ownership/policy; restore a backup instead.
        migrations.RunPython(backfill_organizations),
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='social_stats.organization'),
        ),
    ]
