# Generated by Django 5.2.17 on 2026-10-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0076_organization_tenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcredential',
            name='auth_failure_code',
            field=models.CharField(blank=True, choices=[('token_expired', 'Token expired'), ('revoked', 'Revoked')], default='', editable=False, max_length=32, verbose_name='دلیل خطای احراز هویت'),
        ),
    ]
