# Generated by Django 5.2.17 on 2026-10-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0077_credential_auth_failure_evidence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformpublishlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='platformpublishlog',
            name='account_target_id',
            field=models.PositiveBigIntegerField(verbose_name='شناسه حساب مقصد', default=0, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='platformpublishlog',
            unique_together={('unified_post', 'platform', 'account_target_id')},
        ),
    ]
