# Generated by Django 5.2.17 on 2026-10-06 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0078_composer_account_deliveries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedpost',
            name='intent_key',
            field=models.UUIDField(verbose_name='کلید درخواست نگارش', blank=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedpost',
            unique_together={('client', 'created_by', 'intent_key')},
        ),
    ]
