# Generated by Django 5.2.17 on 2026-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0079_composer_intent_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='provider_metrics',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='شاخص\u200cهای دریافت\u200cشده از سرویس'),
        ),
    ]
