# Generated by Django 5.2.17 on 2026-10-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_stats", "0080_provider_metric_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedreport",
            name="social_account_ids",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
