# Generated by Django 5.2.17 on 2026-10-07 05:06

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_organization_subscriptions(apps, schema_editor):
    Organization = apps.get_model('social_stats', 'Organization')
    Subscription = apps.get_model('social_stats', 'Subscription')
    using = schema_editor.connection.alias
    AIUsageLog = apps.get_model('social_stats', 'AIUsageLog')
    now = timezone.now()
    since = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    period = now.strftime('%Y-%m')
    for organization in Organization.objects.using(using).iterator():
        if Subscription.objects.using(using).filter(organization_id=organization.pk).exists():
            continue
        legacy = list(Subscription.objects.using(using).filter(
            client__organization_id=organization.pk,
        ).order_by('pk'))
        used = AIUsageLog.objects.using(using).filter(
            client__organization_id=organization.pk, created_at__gte=since, cached=False,
        ).count()
        if len(legacy) == 1:
            # Transfer the same row: invoice and provider identifiers stay intact.
            Subscription.objects.using(using).filter(pk=legacy[0].pk).update(
                organization_id=organization.pk, client_id=None,
                usage_counters={**legacy[0].usage_counters, 'ai': {period: used}},
            )
        else:
            # Conflicting workspace subscriptions and delegated agency histories
            # cannot safely determine a tenant's billing authority.
            Subscription.objects.using(using).create(
                organization_id=organization.pk, plan='self-hosted', status='active',
                usage_counters={'ai': {period: used}},
            )



class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0081_shared_report_account_scope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscription_exactly_one_subject',
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='social_stats.organization'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('self-hosted', 'Self-hosted'), ('org-free', 'Organization Free'), ('org-pro', 'Organization Pro'), ('eu-free', 'End-user · Free'), ('eu-pro', 'End-user · Pro'), ('eu-premium', 'End-user · Premium'), ('agency-starter', 'Agency · Starter'), ('agency-growth', 'Agency · Growth'), ('agency-scale', 'Agency · Scale'), ('agency-enterprise', 'Agency · Enterprise')], default='self-hosted', max_length=30),
        ),
        migrations.RunPython(backfill_organization_subscriptions),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('client__isnull', True), ('agency__isnull', True)), models.Q(('organization__isnull', True), ('client__isnull', False), ('agency__isnull', True)), models.Q(('organization__isnull', True), ('client__isnull', True), ('agency__isnull', False)), _connector='OR'), name='subscription_exactly_one_subject'),
        ),
    ]
