# Generated by Django 5.2.17 on 2026-10-09 05:17

import django.db.models.deletion
import social_stats.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0083_alter_notificationpreference_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='social_stats.socialaccount', verbose_name='اکانت'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=social_stats.upload_paths.workspace_image_path, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=social_stats.upload_paths.workspace_image_path, verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(max_length=500, upload_to=social_stats.upload_paths.media_path, verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=social_stats.upload_paths.thumbnail_path, verbose_name='تصویر بندانگشتی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=social_stats.upload_paths.avatar_path, verbose_name='تصویر کاربر'),
        ),
    ]
