# Generated by Django 5.2.17 on 2026-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0087_team_role_presets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcredential',
            name='auth_method',
            field=models.CharField(choices=[('oauth', 'احراز هویت OAuth'), ('manual_token', 'توکن دستی'), ('system_user', 'کاربر سیستمی'), ('managed_bot', 'روبات پروژه')], default='oauth', max_length=20, verbose_name='روش احراز هویت'),
        ),
    ]
