import { test, expect } from '@playwright/test';
import { enMessages as en, faMessages as fa } from '../src/i18n/messages';
import { connectionFixture } from '../src/services/__fixtures__/connections';
test.use({ trace: 'off', screenshot: 'off', video: 'off' });
const base = process.env.E2E_BASE_URL || 'http://127.0.0.1:3000';
const profile = { id:7,name:'Synthetic workspace',company:'Fixture business',email:'team@example.test',phone:'',whatsapp_number:'',website:'',gmb_url:'',business_category:'Technology',brand_description:'Fixture brand',usp:'Fixture strengths',brand_tone:'professional',target_audience:'Fixture audience',gender:'all',business_location:'Fixture city',business_subcategories:[],target_locations:['India'],competitors:[],brand_assets:{logo:'/existing.png'},profile_image:null,product_images:['/product.png'],onboarding_complete:false };
const idea = {id:1,week_number:1,day_of_week:'Monday',scheduled_date:'2026-10-12',platform:'facebook',post_type:'text',topic:'Synthetic topic',caption_hint:'Synthetic caption',hashtag_hints:[],best_time:'10:00',notes:'',is_approved:false,is_added_to_calendar:false};
const calendar = {id:1,month:10,year:2026,month_name:'October',business_type:'technology',location:'Fixture city',target_audience:'Fixture audience',platforms:['facebook'],posts_per_week:1,month_theme:'Synthetic calendar',strategy_notes:'Synthetic strategy',posts:[],generated_at:'2026-10-08T10:00:00Z',ideas:[idea]};
async function fixture(page,family,locale='en',theme='light') {
 const state={staff:false,readDelay:0,status:0,malformed:false,writeStatus:0,writeMalformed:false,delay:0,writes:0,reads:0,empty:false};
 await page.context().addCookies([{name:'socialstats.language',value:locale,url:base},{name:'theme',value:theme,url:base}]);
 await page.addInitScript(language=>{localStorage.setItem('socialstats.language',language);localStorage.setItem('socialstats_cookie_choice',JSON.stringify({version:'2024-11-01',choices:{essential:true,functional:true}}));},locale);
 await page.routeWebSocket('**/ws/**',s=>s.close());
 await page.route('**/api/**',async route=>{
  const req=route.request(),path=new URL(req.url()).pathname,write=!['GET','HEAD'].includes(req.method());
  if(path==='/api/auth/session/')return route.fulfill({json:{authenticated:true,csrfToken:'fixture'}});
  if(path==='/api/auth/me/')return route.fulfill({json:{id:1,role:state.staff?'staff':'client',account_type:'legacy',client_id:state.staff?null:7,workspace_id:state.staff?null:7,first_name:'Synthetic',last_name:'User',permissions:{}}});
  if(path==='/api/workspaces/')return route.fulfill({json:[{id:7,name:'Fixture one',company:'Fixture one'},{id:8,name:'Fixture two',company:'Fixture two'}]});
  if(path==='/api/public/lookups/')return route.fulfill({json:{}});
  if(/\/connections\/$/.test(path))return route.fulfill({json:connectionFixture()});
  const target=family==='onboarding'?path==='/api/workspaces/7/':path.startsWith('/api/ai/post-ideas/');
  if(target){if(write){state.writes++;if(state.delay)await new Promise(r=>setTimeout(r,state.delay));if(state.writeStatus)return route.fulfill({status:state.writeStatus,json:{}});if(state.writeMalformed)return route.fulfill({json:{}});}else{state.reads++;if(state.readDelay)await new Promise(r=>setTimeout(r,state.readDelay));if(state.status)return route.fulfill({status:state.status,json:{}});if(state.malformed)return route.fulfill({json:{}});}}
  if(path==='/api/workspaces/7/'){
   const row={...profile};if(write){for(const match of (req.postData()||'').matchAll(/name="([^"]+)"\r\n\r\n([^]*?)\r\n--/g)){const [,key,value]=match;row[key]=['business_subcategories','target_locations','brand_assets','product_images'].includes(key)?JSON.parse(value):value;}row.onboarding_complete=row.onboarding_complete===true||row.onboarding_complete==='true';}return route.fulfill({json:row});
  }
  if(path==='/api/ai/post-ideas/')return route.fulfill({json:write?{...calendar,...req.postDataJSON()}:state.empty?[]:[{...calendar,month_theme:new URL(req.url()).searchParams.get('workspace_id')==='8'?'Second calendar':calendar.month_theme,month_name:new URL(req.url()).searchParams.get('workspace_id')==='8'?'November':calendar.month_name}]});
  if(path.endsWith('/approve-all/'))return route.fulfill({json:{approved:1,total:1}});
  if(path.endsWith('/add-to-calendar/'))return route.fulfill({json:{created:1,message:'1 post added to your content calendar as drafts.'}});
  if(path.includes('/ideas/'))return route.fulfill({json:{...idea,...req.postDataJSON()}});
  return route.fulfill({json:[]});
 });return state;
}
const paths={onboarding:'/dashboard/onboarding',ideas:'/dashboard/analytics/post-ideas'};
for(const family of ['onboarding','ideas'])for(const status of [401,403,404,429,503,'malformed'])test(`${family} checked initial reader ${status} preserves shell and local recovery`,async({page})=>{
 const s=await fixture(page,family);if(status==='malformed')s.malformed=true;else s.status=status;
 await page.goto(paths[family]);if(status===401){await expect(page).toHaveURL(/\/login/);await expect(page.getByRole('region',{name:en[family==='ideas'?'ideas.history':'onboarding.profile']})).toHaveCount(0);return;}const area=page.getByRole('region',{name:en[family==='ideas'?'ideas.history':'onboarding.profile'],exact:true});
 await expect(area.getByRole('button',{name:en['recovery.retry'],exact:true})).toBeVisible();await expect(page.getByText(en['ideas.empty'],{exact:true})).toHaveCount(0);
 if(family==='onboarding')await expect(page.getByPlaceholder('Your company name')).toHaveCount(0);else if(![403,404].includes(status))await expect(page.getByRole('heading',{name:'Generate Your Content Calendar'})).toBeVisible();
 s.status=0;s.malformed=false;await area.getByRole('button',{name:en['recovery.retry'],exact:true}).click();await expect(area.getByRole('button',{name:en['recovery.retry'],exact:true})).toHaveCount(0);await expect(area).toBeFocused();
 if(family==='onboarding')await expect(page.getByPlaceholder('Your company name')).toHaveValue('Fixture business');else await expect(page.getByRole('button',{name:/October 2026/})).toBeVisible();
});
for(const malformed of [false,true])test(`onboarding ${malformed?'malformed':'503'} save retains draft and cannot advance or replay`,async({page,context})=>{
 const s=await fixture(page,'onboarding');await page.goto(paths.onboarding);const company=page.getByRole('textbox',{name:'Business Name *'});await expect(company).toHaveValue('Fixture business');await company.fill('Edited fixture');s.writeStatus=malformed?0:503;s.writeMalformed=malformed;
 await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByText(en['onboarding.uncertain'],{exact:true})).toBeVisible();await expect(company).toHaveValue('Edited fixture');await expect(page.getByRole('button',{name:'Next',exact:true})).toBeDisabled();expect(s.writes).toBe(1);
 await context.setOffline(true);await context.setOffline(false);expect(s.writes).toBe(1);await page.getByRole('button',{name:en['account.checkStatus'],exact:true}).click();await expect(page.getByRole('button',{name:en['ideas.acknowledge'],exact:true})).toBeVisible();await expect(company).toHaveValue('Edited fixture');expect(s.writes).toBe(1);
});
test('onboarding only a matching backend acknowledgment advances and preserves asset metadata',async({page})=>{
 const s=await fixture(page,'onboarding');await page.goto(paths.onboarding);const company=page.getByRole('textbox',{name:'Business Name *'});await expect(company).toHaveValue('Fixture business');await company.fill('Edited fixture');let body='';page.on('request',r=>{if(r.method()==='PATCH')body=r.postData()||'';});await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByPlaceholder('Describe your brand in a few sentences...')).toBeVisible();expect(s.writes).toBe(1);expect(body).toContain('/product.png');expect(body).toContain('/existing.png');
});
for(const malformed of [false,true])test(`ideas keyboard edit ${malformed?'malformed':'503'} retains draft without replay`,async({page,context})=>{
 const s=await fixture(page,'ideas');await page.goto(paths.ideas);await page.getByRole('button',{name:/October 2026/}).click();const edit=page.getByRole('button',{name:en['ideas.editTopic'],exact:true});await edit.focus();await page.keyboard.press('Enter');const input=page.getByRole('textbox',{name:en['ideas.editTopic'],exact:true});await input.fill('Edited topic');s.writeStatus=malformed?0:503;s.writeMalformed=malformed;await page.getByRole('button',{name:en['ideas.saveEdit'],exact:true}).click();await expect(page.getByText(en['ideas.uncertain'],{exact:true})).toBeVisible();await expect(input).toHaveValue('Edited topic');expect(s.writes).toBe(1);await context.setOffline(true);await context.setOffline(false);expect(s.writes).toBe(1);
});
test('ideas empty history is explicit, unlike failed history',async({page})=>{const s=await fixture(page,'ideas');s.empty=true;await page.goto(paths.ideas);await expect(page.getByText(en['ideas.empty'],{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Generate Your Content Calendar'})).toBeVisible();});
test('ideas duplicate approval is suppressed and invalid acknowledgment never approves',async({page})=>{const s=await fixture(page,'ideas');await page.goto(paths.ideas);await page.getByRole('button',{name:/October 2026/}).click();s.writeMalformed=true;s.delay=500;const button=page.getByRole('button',{name:'✓ Approve All',exact:true});await button.click();await expect(button).toBeDisabled();await expect(page.getByText(en['ideas.uncertain'],{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'✓ Approve',exact:true})).toBeVisible();expect(s.writes).toBe(1);});
for(const [family,locale,theme,width] of [['onboarding','fa','dark',360],['ideas','en','light',1440]])test(`safe editor recovery evidence ${family}`,async({page})=>{const s=await fixture(page,family,locale,theme);s.status=503;await page.setViewportSize({width,height:900});await page.goto(paths[family]);if(process.env.E2E_UI_BASELINE)await page.waitForTimeout(1200);else await expect(page.getByRole('region',{name:(locale==='fa'?fa:en)[family==='ideas'?'ideas.history':'onboarding.profile']}).getByRole('button',{name:(locale==='fa'?fa:en)['recovery.retry'],exact:true})).toBeVisible();await page.screenshot({path:`e2e/evidence/editor/${family}-${process.env.E2E_UI_BASELINE?'before':'after'}-${locale}-${theme}-${width}.png`,fullPage:true});});

test('staff workspace change excludes late history from the previous context',async({page})=>{const s=await fixture(page,'ideas');s.staff=true;s.readDelay=1000;await page.goto('/admin/analytics/post-ideas?client=7');const selector=page.locator('main').getByRole('combobox',{name:en['posts.workspace'],exact:true});await selector.selectOption('8');await expect(page).toHaveURL(/client=8/);await expect(page.getByRole('button',{name:/November 2026/})).toBeVisible();await expect(page.getByRole('button',{name:/October 2026/})).toHaveCount(0);});
test('slow initial onboarding read is explicit and cannot initialize a guessed form',async({page})=>{const s=await fixture(page,'onboarding');s.readDelay=1000;await page.goto(paths.onboarding);await expect(page.getByRole('region',{name:en['onboarding.profile']}).getByText(en['recovery.loading'],{exact:true})).toBeVisible();await expect(page.getByPlaceholder('Your company name')).toHaveCount(0);await expect(page.getByPlaceholder('Your company name')).toHaveValue('Fixture business');});
test('known calendar creation followed by history failure preserves the acknowledgment and has no replay',async({page})=>{const s=await fixture(page,'ideas');await page.goto(paths.ideas);await page.getByRole('button',{name:/October 2026/}).click();s.status=503;await page.getByRole('button',{name:/Add All to Calendar/}).click();await expect(page.getByText('1 post added to your content calendar as drafts.',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:en['ideas.history']}).getByText(en['recovery.stale'],{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:en['ideas.editTopic']})).toHaveText('Synthetic topic');expect(s.writes).toBe(1);});
